services:
  # Azure Blob Storage emulator
  azure-storage:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000 -l data"
    ports:
      - "10000:10000"

  # AWS S3 Storage emulator
  aws-storage:
    image: gresau/localstack-persist:3
    ports:
      - "4566:4566"
    volumes:
      - "./volume:/persisted-data"

  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - ./seed-scripts/sql/:/docker-entrypoint-initdb.d/
      - ./seed-scripts/sql/.pgpass/:/usr/local/lib/.pgpass
    environment:
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=ecr_viewer_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 20
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1!
    ports:
      - "1433:1433"
    volumes:
      - ./sql:/var/opt/mssql/scripts
      - ./sql-scripts:/usr/config
    entrypoint: /usr/config/entrypoint.sh
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Password1! -Q 'IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ECR_DATA') SELECT 1 ELSE SELECT 0' -C | grep -q 1",
        ]
      interval: 20s
      timeout: 10s
      retries: 5
